# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 070351d6ccbcc180e2d8fd6db9b3697d3dc51b61d0ea1f16b9a2adebdfa3ca667ddd0c8935378f53999b77d4d09532140852a514dd7120948f494667dfd74e25

test:
  secret_key_base: 42c375a6f50ea90eef845ccffb0dd785567136d0ad49d266177ebb74ba5fb983c75cf68219795ab72afb8c868221c2392f6c4e4ee35323be3f2a343a5918764c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
